### PR TITLE
1251070 - broken link fixed

### PR DESCRIPTION
**Pull request by v-hearya**

### CODE REVIEW

**Comment by jmazzotta** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr/blob/master/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md) | :warning:Warning | | [Details](#user-content-Web-Apps-Server-loc%2Fconfigure-office-web-apps-for-sharepoint-2013.md)

<a name="Web-Apps-Server-loc%2Fconfigure-office-web-apps-for-sharepoint-2013.md"></a>
### [Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr/blob/master/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md)
 - **Line 134**: **[Warning]** Invalid file link:(~/deploy-office-web-apps-server#deploy-a-multi-server-load-balanced-office-web-apps-server-farm-that-uses-https).
 - **Line 134**: **[Warning]** Invalid file link:(~/%5Cdeploy-office-web-apps-server#deploy-a-single-server-office-web-apps-server-farm-that-uses-https).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C27%5C185abfa8-13a6-e6b1-cc0b-168f4cae31a7%5CPullRequest%5C201806272104076732-2%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=t6krzzZdvS6VUia6V3lz%2FM6uwsoEGg%2FHriIU%2Be%2FWWOI%3D&st=2018-06-27T21%3A00%3A07Z&se=2018-07-28T21%3A05%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jmazzotta** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr/blob/master/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md) | :warning:Warning | | [Details](#user-content-Web-Apps-Server-loc%2Fconfigure-office-web-apps-for-sharepoint-2013.md)

<a name="Web-Apps-Server-loc%2Fconfigure-office-web-apps-for-sharepoint-2013.md"></a>
### [Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr/blob/master/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md)
 - **Line 134**: **[Warning]** Invalid file link:(~/deploy-office-web-apps-server#deploy-a-multi-server-load-balanced-office-web-apps-server-farm-that-uses-https).
 - **Line 134**: **[Warning]** Invalid file link:(~/%5Cdeploy-office-web-apps-server#deploy-a-single-server-office-web-apps-server-farm-that-uses-https).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C29%5C185abfa8-13a6-e6b1-cc0b-168f4cae31a7%5CPullRequest%5C201806291958162216-2%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=NlStYJT9LwLwvCzqXWj84k2brQ6%2F5IJhKU7sWmOnWbo%3D&st=2018-06-29T19%3A54%3A10Z&se=2018-07-30T19%3A59%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jmazzotta** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr/blob/master/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md) | :warning:Warning | | [Details](#user-content-Web-Apps-Server-loc%2Fconfigure-office-web-apps-for-sharepoint-2013.md)

<a name="Web-Apps-Server-loc%2Fconfigure-office-web-apps-for-sharepoint-2013.md"></a>
### [Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr/blob/master/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md)
 - **Line 134**: **[Warning]** Invalid file link:(~/deploy-office-web-apps-server#deploy-a-multi-server-load-balanced-office-web-apps-server-farm-that-uses-https).
 - **Line 134**: **[Warning]** Invalid file link:(~/%5Cdeploy-office-web-apps-server#deploy-a-single-server-office-web-apps-server-farm-that-uses-https).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C29%5C185abfa8-13a6-e6b1-cc0b-168f4cae31a7%5CPullRequest%5C201806292014139022-2%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=iH2l0Da1u3OqumX2LrjZT4OOwNezS893CF0iLcqJ7h8%3D&st=2018-06-29T20%3A10%3A09Z&se=2018-07-30T20%3A15%3A09Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jmazzotta** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr/blob/master/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md) | :warning:Warning | | [Details](#user-content-Web-Apps-Server-loc%2Fconfigure-office-web-apps-for-sharepoint-2013.md)
[.openpublishing.publish.config.json](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr/blob/master/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

<a name="Web-Apps-Server-loc%2Fconfigure-office-web-apps-for-sharepoint-2013.md"></a>
### [Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr/blob/master/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md)
 - **Line 134**: **[Warning]** Invalid file link:(~/deploy-office-web-apps-server#deploy-a-multi-server-load-balanced-office-web-apps-server-farm-that-uses-https).
 - **Line 134**: **[Warning]** Invalid file link:(~/%5Cdeploy-office-web-apps-server#deploy-a-single-server-office-web-apps-server-farm-that-uses-https).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C29%5C185abfa8-13a6-e6b1-cc0b-168f4cae31a7%5CPullRequest%5C201806292023297046-2%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Nvcx8slczUz95%2FWzCNWgyxDv2Z2U52Rez8XnUVKYU7k%3D&st=2018-06-29T20%3A19%3A24Z&se=2018-07-30T20%3A24%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jmazzotta** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr/blob/master/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md) | :warning:Warning | | [Details](#user-content-Web-Apps-Server-loc%2Fconfigure-office-web-apps-for-sharepoint-2013.md)
[.openpublishing.publish.config.json](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr/blob/master/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

<a name="Web-Apps-Server-loc%2Fconfigure-office-web-apps-for-sharepoint-2013.md"></a>
### [Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr/blob/master/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md)
 - **Line 134**: **[Warning]** Invalid file link:(~/deploy-office-web-apps-server#deploy-a-multi-server-load-balanced-office-web-apps-server-farm-that-uses-https).
 - **Line 134**: **[Warning]** Invalid file link:(~/%5Cdeploy-office-web-apps-server#deploy-a-single-server-office-web-apps-server-farm-that-uses-https).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C29%5C185abfa8-13a6-e6b1-cc0b-168f4cae31a7%5CPullRequest%5C201806292031171061-2%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=YbPm%2FyXFvpSgGof3P80oVySZlhnjqKHSofQMiW7t%2BI0%3D&st=2018-06-29T20%3A27%3A11Z&se=2018-07-30T20%3A32%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jmazzotta** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr/blob/master/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/office/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013?branch=pr-en-us-2) | [Details](#user-content-Web-Apps-Server-loc%2Fconfigure-office-web-apps-for-sharepoint-2013.md)

<a name="Web-Apps-Server-loc%2Fconfigure-office-web-apps-for-sharepoint-2013.md"></a>
### [Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/v-hearya/OfficeDocs-OfficeOnlineServer-Test-loc-pr/blob/master/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md)
 - **Line 134**: **[Warning]** Invalid file link:(~/deploy-office-web-apps-server#deploy-a-single-server-office-web-apps-server-farm-that-uses-https).
 - **Line 134**: **[Warning]** Invalid file link:(~/deploy-office-web-apps-server#deploy-a-multi-server-load-balanced-office-web-apps-server-farm-that-uses-https).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C4%5C185abfa8-13a6-e6b1-cc0b-168f4cae31a7%5CPullRequest%5C201807041628291093-2%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zDM66GQFqdMdyVUqqHnTIlx6EZxya7FHh73U0imyYhE%3D&st=2018-07-04T16%3A24%3A27Z&se=2018-08-04T16%3A29%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
Closing PR without merging as issue has been fixed

**Pull request closed without merging**
